"""empty message

Revision ID: 34526f308e5e
Revises: 96963e5310ec
Create Date: 2018-11-14 04:12:33.149718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34526f308e5e'
down_revision = '96963e5310ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email2', table_name='users')
    op.drop_column('users', 'email2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email2', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email2', 'users', ['email2'], unique=True)
    # ### end Alembic commands ###
